name: CI - Angular Build Validations

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  validate-build:
    if: github.repository != 'RaFFoOOo/Coding-Standards'
    uses: ./.github/workflows/shared-build-angular.yml
    with:
      node-version: ${{ vars.NODE_VERSION || '20' }}
